### ISSUE TITLE
제보 받은 UI 자잘한 에러

### ISSUE THREAD

**Issue by Parkhanyoung** [maeil-mail/maeil-mail-fe#102]
shout out to @Todari 🫰🏻

## 간략한 설명
1. 개인정보방침 clickable함을 보여주기 위해 underline 추가
<img width="225" alt="스크린샷 2024-10-30 오전 12 02 24" src="https://github.com/user-attachments/assets/a8d4578d-d369-4609-a8ac-8f83df26aa71">

2. 인풋을 포커스하여 키보드를 띄우면, 모달 스크롤이 가능해지는 현상

https://github.com/user-attachments/assets/03a0a79a-f352-4055-983b-f1ac39ed0573

3. 스크롤 최하단에서 추가 스크롤 시 헤더의 요소가 뭉개지는 현상

https://github.com/user-attachments/assets/3321d8f3-3bc5-4757-87b0-619b993f908b

4. 인증번호 인풋을 number 타입으로 수정

**Comment by brgndyy** [comment]
이거 제가 이 이슈 번호로 브랜치 파서 작업하겠습니다~!

**Comment by Parkhanyoung** [comment]
앗 너무 감사합니다! 🥲
(1, 4번은 다른 PR에 포함되어 있어서 제외하고 하셔도 될 것 같아요!)

**Comment by Parkhanyoung** [comment]
#115 에서 해결하므로 닫습니다.
