### ISSUE TITLE
useSubscribe 리팩토링

### ISSUE THREAD

**Issue by Parkhanyoung** [maeil-mail/maeil-mail-fe#113]
## 간략한 설명
<img width="903" alt="스크린샷 2024-11-01 오후 5 27 58" src="https://github.com/user-attachments/assets/c8d6f058-b466-41f4-a88c-3a4e130f5609">

useSubscribe가 타르 구덩이가 되기 전에 리팩토링하여 유지보수성을 높입니다.

**Comment by brgndyy** [comment]
ㅋㅋㅋㅋㅋㅋ
