### ISSUE TITLE
41번 프론트 문제에서 문법적 오류

### ISSUE THREAD

**Issue by Jamkris** [maeil-mail/maeil-mail-fe#128]
## 간략한 설명
https://www.maeil-mail.kr/question/41
41번 문제에 문법적 에러가 발생된 부분이 있습니다.

### 구현 목록
"쓰로틀(throttle)**는"을  "**쓰로틀(throttle)**은"로 수정해주세요!! 또한 *기호도 없는게 가독성이 더 좋은 거 같습니다..

**Comment by brgndyy** [comment]
말씀 감사합니다 :) 얼른 반영하도록 하겠습니다!

**Comment by Parkhanyoung** [comment]
수정 완료했습니다!
제보 주셔서 정말 감사합니다. 아직 부족함이 많지만, 열심히 발전해 나가겠습니다!
혹시, 확인 되시면 issue close 부탁드립니다. 🙂

**Comment by Jamkris** [comment]
감사합니다.
