### ISSUE TITLE
UI 관련 피드백 반영

### ISSUE THREAD

**Issue by Parkhanyoung** [maeil-mail/maeil-mail-fe#131]
## 목록
UI 관련 유저 피드백을 반영합니다.

- [x] 인증 모달 백그라운드 누를 때 닫히지 않고 닫기 버튼으로만 닫을 수 있도록 수정
- [x] 404 페이지 크기 줄이기
- [x] 구독 신청 완료 모달에서 개인 별 사이클이 따로 돌아서 첫 메일부터 다 받아볼 수 있음을 알려주기
- [ ] 네이버 로고 중앙 정렬 안되도록 수정하기

**Comment by ojj1123** [comment]
안녕하세요!

링크드인에서 "매일메일" 서비스 보고 구독 중인 한 유저(?)입니다. 일단 좋은 프로덕트 만들어주셔서 감사합니다.
사용하면서 궁금한 부분이 있어 가볍게 코멘트 남겨봅니다!

1. 질문 콘텐츠들은 어떻게 생성하고 관리하시나요? 질문과 답변을 자동생성(e.g. Gen AI)하는지 아니면 손수 작성(CMS 도구 등)하시는건지 궁금해요!
2. 콘텐츠는 지속적으로 추가되는건가요?

그리고 한가지 피드백도 드리고 싶습니다!

> 다들 면접 대비는 어떻게 하시나요? 면접 준비가 아니더라도 개념/이론 학습은 어떻게 하고 계신가요?
> -프로젝트 readme 중

이 서비스의 기획의도가 "면접대비" + "개념 학습"인 것으로 보여요! 그래서 몇몇 개념들은 이미지와 함께 설명해주면 이해하는데 도움이 될 것 같아요! 예를 들면 [이벤트 루프에 대한 설명](https://www.maeil-mail.kr/question/15)은 이벤트 루프와 Web API, Call stack의 동작을 이미지나 gif로 표현하는 것처럼요. CS 등 이론 공부를 할 때 이런 이미지가 큰 도움이 됐던 경험이 있어서 가볍게 이야기해봅니당! 콘텐츠의 질에 대한 피드백네요 :)

![image](https://github.com/user-attachments/assets/1b58657a-449f-4eaf-93d5-d13c929b238b)

감사합니다 :)

**Comment by Parkhanyoung** [comment]
안녕하세요, 정진님. 매일메일에 관심을 갖고 이렇게 직접 코멘트 남겨주셔서 감사드립니다. 🙇🏻‍♂️

> 질문 콘텐츠들은 어떻게 생성하고 관리하시나요? 질문과 답변을 자동생성(e.g. Gen AI)하는지 아니면 손수 작성(CMS 도구 등)하시는건지 궁금해요!

컨텐츠는 팀원들이 직접 작성하고 있습니다. 자동생성을 하면 빠르겠지만, 아직은 AI를 이용했을 때 퀄리티 면에서 한계가 있는 것 같아서요! 글의 구조를 잡거나, 검토를 하는 데에만 부분적으로 활용하고 있습니다.

> 콘텐츠는 지속적으로 추가되는건가요?

네. 서비스명처럼 매일매일 작성하여 추가하고 있습니다. 😄

> 몇몇 개념들은 이미지와 함께 설명해주면 이해하는데 도움이 될 것 같아요!

좋은 피드백 감사드립니다. :)
짚어주신 대로 이벤트 루프와 같이 이미지가 설명에 큰 도움이 될 만한 내용에는 이미지를 첨부하는 것도 좋을 것 같다는 생각이 드네요.
우선은 면접을 전제로 하는 만큼, 최대한 글(말)만으로 풀어내려 한 경향이 있었던 것 같습니다.
앞으로 복잡한 개념을 설명할 때에는 이미지 첨부를 고려하겠습니다!
