### ISSUE TITLE
질문 57번 문자열 에러

### ISSUE THREAD

**Issue by Jamkris** [maeil-mail/maeil-mail-fe#147]
## 간략한 설명
https://www.maeil-mail.kr/question/57

![image](https://github.com/user-attachments/assets/47a84a3f-37f1-420d-b7fa-b8a3b4c4c990)

### 구현 목록
"단일 콜 스택" 부분에 에러 문자열이 들어간거 같습니다. 모바일에서만 나타나는 현상인거 같습니다. PC에서는 같은 현상이 일어나지 않습니다. 단순히 띄어쓰기 문제인듯합니다.
사파리, 아크, 크롬 모두에서 동일하게 일어나네요...

**Comment by Parkhanyoung** [comment]
안녕하세요 승현님, 디테일하게 살펴보고 피드백 남겨주셔서 정말 감사합니다. 🙂

수정 완료했습니다. 확인 후 고쳐졌다면 Issue close 부탁드리겠습니다!

**Comment by Jamkris** [comment]
예쁘게 잘 나오네요. 감사합니다. ☺️
