### ISSUE TITLE
프론트엔드 질문 63번 문자열 에러

### ISSUE THREAD

**Issue by Jamkris** [maeil-mail/maeil-mail-fe#153]
## 간략한 설명
https://www.maeil-mail.kr/question/63

<img width="379" alt="image" src="https://github.com/user-attachments/assets/e52916c9-5008-49b3-94e6-dd345689b8ab">
<img width="379" alt="image" src="https://github.com/user-attachments/assets/e70a1669-4496-4671-bf12-0fb49f0a526f">

### 구현 목록
"변수를 undefined로 설정한다고 해서 0자바스크립트가" 부분에 에러 문자열이 들어간거 같습니다. 모바일에서만 나타나는 현상인거 같습니다. PC에서는 같은 현상이 일어나지 않습니다. 단순히 띄어쓰기 문제인듯합니다.
사파리, 아크, 크롬 모두에서 동일하게 일어나네요...

**Comment by Parkhanyoung** [comment]
안녕하세요 승현님, 제보 감사합니다. 바로 수정 완료했습니다.
비슷한 문제가 반복되는 것 같네요. 관련해서 한번 알아 보겠습니다!

https://www.maeil-mail.kr/question/63

확인해되시면 issue close 부탁드립니다!

**Comment by Jamkris** [comment]
넵 감사합니다!
