### ISSUE TITLE
프론트엔드 질문 73번 문자열 에러

### ISSUE THREAD

**Issue by Jamkris** [maeil-mail/maeil-mail-fe#157]
## 간략한 설명
https://www.maeil-mail.kr/question/73

<img width="379" alt="image" src="https://github.com/user-attachments/assets/44ac7c29-92cc-45c3-98db-aa49e8166493">

### 구현 목록
"resolve와 fulfilled는 Promise에서 비동기 처리시" 부분에 에러 문자열이 들어간거 같습니다. 모바일에서만 나타나는 현상인거 같습니다. PC에서는 같은 현상이 일어나지 않습니다. 단순히 띄어쓰기 문제인듯합니다.
사파리, 아크, 크롬 모두에서 동일하게 일어나네요...

**Comment by Parkhanyoung** [comment]
안녕하세요 승현님, 이번에도 제보 주셔서 감사합니다. 수정 완료했습니다!
이후의 질문들 모두 확인해서 유사한 오류가 없도록 조치했습니다!

https://www.maeil-mail.kr/question/73

확인해되시면 issue close 부탁드립니다!

**Comment by Jamkris** [comment]
감사합니다☺️
