### ISSUE TITLE
[Bug] : 구독 신청 버튼 CORS에러 발생

### ISSUE THREAD

**Issue by moong23** [maeil-mail/maeil-mail-fe#83]
현재 서비스에서 구독 서비스 신청 버튼을 누를 시 CORS 에러가 발생합니다!

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/b971bec1-ab47-42a9-a251-f9f569a24778">

https://github.com/user-attachments/assets/95dd7851-d608-4360-869c-5116103fd2b0

**Comment by Parkhanyoung** [comment]
안녕하세요, 에러 제보해주셔서 정말 감사합니다. 빠르게 처리한 후 다시 코멘트 드리겠습니다!

**Comment by le2sky** [comment]
안녕하세요. 제보 감사합니다! 현재 해당 문제 조치해놨는데요. 
여전히 문제가 발생하신다면 빠르게 조치하도록 하겠습니다.
불편을 드려 죄송합니다. 🥲
