### ISSUE TITLE
이메일 유효성 검사 로직 개선

### ISSUE THREAD

**Issue by SJvaca30** [maeil-mail/maeil-mail-fe#96]
## 간략한 설명

안녕하세요! 현재 이메일 유효성 검사 로직에 대해 몇 가지 개선점을 제안드리고 싶습니다.

## 수정된 내용
 - 연속된 점(.) 사용 불가
 - 이메일 주소가 점(.)으로 시작할 수 없음
 - 이모지 및 유니코드 문자 사용 제한
 - 최대 길이 제한 (254자)
 - 연속된 특수문자 사용 제한

## 테스트 케이스
기존에 아래와 같은 케이스들이 통과되어 수정했습니다.
```
test@test..com
.test@domain.com
test😎@domain.com
매우 긴 이메일 주소
test##@domain.com
```

**Comment by Parkhanyoung** [comment]
코드 살펴봐주시고 중요한 부분을 잘 짚어주셔서 정말 감사드립니다.
이런 따뜻한 관심이 큰 힘이 됩니다. 🥲
살펴보고 다시 코멘트 드리겠습니다! :)

**Comment by brgndyy** [comment]
안녕하세요 먼저 이렇게 PR 올려주시고 관심 가져주셔서 감사합니다 :)

작성해주신 유효성 검사 조건들은 저희가 놓친 부분인데, 이렇게 제보해주신 덕분에 로직을 더 보강할수 있을거 같습니다.
상수화라던지, 조건에 따른 분기처리 등 팀끼리의 코드 컨벤션이 따로 있는지라 머지하기에는 조금 어려움이 있을거 같습니다.

짚어주신 부분들은 저희가 빠른 시일내에 추가하여 보강하겠습니다 🙇

다시 한번 부족한 부분 짚어주셔서 감사드리며, 앞으로도 말씀 주시면 빠르게 반영하도록 하겠습니다! 감사합니다.
